### ISSUE TITLE
Fix logic for determining course delivery mode

### ISSUE THREAD

**Issue by eamonma** [sqrl-planner/sqrl-client#13]
For some reason, U of T keeps changing the course delivery mode abbreviations. This has caused the need to update the server database, but the new respective types have been disregarded in the client.

**Comment by galacticglum** [comment]
How deep is this issue in our frontend logic? We should probably refactor some of the code (if possible) to anticipate changes like this.

**Comment by eamonma** [comment]
I agree. Perhaps separating some of the types out would be a good idea. For now, there is a hotfix implemented in PR #14.
