### ISSUE TITLE
Add ability to Mark Course as No Credit

### ISSUE THREAD

**Issue by eamonma** [sqrl-planner/sqrl-client#27]
Applicable scenarios: 
- courses like PDC​320 is not worth a credit; currently, Sqrl has no way of knowing this.

If a course is marked as No Credit, it is not included in credit calculations in Overview.

**Comment by galacticglum** [comment]
I think this should be somewhat automated for courses such as PDC320 that are never worth any credits. We should be able to parse that from course metadata and populate and field in the db.

**Comment by eamonma** [comment]
I'm not sure if this can be inherently inferred from the data. One possibility is that if a course does not have a breadth category it's no credit, but we'd have to double check every course for that.
