### ISSUE TITLE
html blocks from course data not rendering properly

### ISSUE THREAD

**Issue by galacticglum** [sqrl-planner/sqrl-client#4]
HTML blocks are not rendering properly (escaped). See below:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/9789945/169655693-f0afe546-ca52-4c34-a60d-15a7245e753f.png">
![image](https://user-images.githubusercontent.com/9789945/169656038-2d022d70-cf33-42f8-8d10-dd371ca66f24.png)

**Comment by eamonma** [comment]
Closed per #19
