### ISSUE TITLE
Schedule renaming

### ISSUE THREAD

**Issue by GregSherman** [sqrl-planner/sqrl-client#62]
Couple things acting up with the renaming to fix:

- [x] After renaming and pressing enter, every subsequent 'enter' will bring up the green notification 
- [x] After renaming and pressing enter, the very next mouse click anywhere will bring up the green notification
- [x] Clicking on and then off of the name field will bring up the notification despite having no input

**Comment by eamonma** [comment]
I think issue 1 is resolved in the latest build.

**Comment by eamonma** [comment]
Close by #74
