### ISSUE TITLE
Add `<title>` tag with Helmet 😎 

### ISSUE THREAD

**Issue by kaspar-p** [sqrl-planner/sqrl-client#9]

**Comment by eamonma** [comment]
As we are using Next.js, we would be using `Head` to achieve this. Perhaps name the issue with the issue itself, rather than implementation details (which can be discussed in the comments).

**Comment by kaspar-p** [comment]
Helmet works on NextJS apps too, btw, tho. i use it on my site

**Comment by eamonma** [comment]
> Helmet works on NextJS apps too, btw, tho. i use it on my site

Is there a reason you prefer it?

**Comment by kaspar-p** [comment]
no
