### ISSUE TITLE
Update title of timetable as soon as the name changes

### ISSUE THREAD

**Issue by eamonma** [sqrl-planner/sqrl-client#90]
**Describe the bug**
Right now, the document title shown in the browser does not change as soon as one changes the name of the timetable; there needs to be a refresh for the title to update.

**To Reproduce**
1. Go to a timetable, note its name and the document title
2. Change the name of the timetable
3. Notice that the document title is as original

**Expected behavior**
The document title should be updated

**Comment by kaspar-p** [comment]
this one is me too
