### ISSUE TITLE
Change the background color of a timetable when hovering on main page

### ISSUE THREAD

**Issue by kaspar-p** [sqrl-planner/sqrl-client#91]
**Is your feature request related to a problem? Please describe.**
The only thing that is different when the cursor hovers over a timetable is the cursor changes from normal to pointer on the main page. 

**Describe the solution you'd like**
To be consistent with the 'Create a new timetable' section, I think that the timetables should darken or lighten a little (depending on the mode) when you are hovering over it.

**Comment by kaspar-p** [comment]
how is this not planned. its literally hover indicator. every other button / clickable has it.

**Comment by kaspar-p** [comment]
im using griddy

**Comment by eamonma** [comment]
@kaspar-p If you'd like to take this, you can dim the card on hover

**Comment by eamonma** [comment]
Closed by #97
